### ISSUE TITLE
All tests broken in latest updates to Proteus (82975c1)?

### ISSUE THREAD

**Issue by nerisaurus** [erdc-cm/air-water-vv#108]
As far as I can tell, all tests (I've tried almost all of them, but there could be some that missed my review) in both 2d and 3d directories crash with the latest Proteus build.  I don't know if this is:
- Us falling out of compatibility with newer standards for Proteus.
- A bug in Proteus or our codes.
- Or just a failure of my own setup.

I'd like a second check on this, and perhaps someone more familiar with Proteus could give that project a more informative idea of what's going wrong.  Here is an example error that is very typical of the errors that are coming up for me (each is slightly different due to different files, of course, but the TypeErrors and SubgridErrors are pretty universal).

`Traceback (most recent call last):
  File "/home/chluser/proteus/linux2/bin/parun", line 5, in <module>
    pkg_resources.run_script('proteus==1.1.0', 'parun')
  File "/home/chluser/proteus/linux2/lib/python2.7/site-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/chluser/proteus/linux2/lib/python2.7/site-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/home/chluser/proteus/linux2/lib/python2.7/site-packages/proteus-1.1.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/parun", line 296, in <module>
    nList.append(__import__(nModule))
  File "./twp_navier_stokes_n.py", line 30, in <module>
    subgridError = RANS2P.SubgridError(coefficients,nd,lag=ns_lag_subgridError,hFactor=hFactor)
  File "/home/chluser/proteus/linux2/lib/python2.7/site-packages/proteus-1.1.0-py2.7-linux-x86_64.egg/proteus/mprans/RANS2P.py", line 37, in __init__
    log("RANS2P.SubgridError: lagging requested but must lag the first step; switching lagging off and delaying")
TypeError: a float is required
`

**Comment by nerisaurus** [comment]
Talked to Alistair and there should be a fix to it.  Problem is in Proteus' RANS2P files.
